### PR TITLE
Add SetFlipMode() function

### PR DESCRIPTION
**Pull request by mitul93**
Added registers and constants from Sapera sdk related to horizontal flip.

### CODE REVIEW

**Comment by julian59189** [comment]
Where do we call the flip function?

**Comment by deadprogram** [comment]
> Where do we call the flip function?

In the new PR in Spyglass, I think.

**Comment by mitul93** [comment]
> Where do we call the flip function?

New PR for spyglass on its way. We call `SetFlipMode()` in spyglass to enable/disable horizontal flip.

**Comment by deadprogram** [comment]
Thanks for the PR @mitul93 now merging.

**Pull request merged**
